import type { SimulationData } from "./types";
import { createContext } from "./types";
import { drawPageHeader, drawPageFooter } from "./helpers";
import { getNarrativeAct, getNarrativeTransition } from "../brandContent";

// Section renderers
import { renderCover } from "./sections/cover";
import { renderProjectSnapshot } from "./sections/projectSnapshot";
import { renderKPIResults } from "./sections/kpiResults";
import { renderInvestmentBreakdown } from "./sections/investmentBreakdown";
import { renderRoofConfiguration } from "./sections/roofConfiguration";
import { renderFinancialProjections } from "./sections/financialProjections";
import { renderAssumptions } from "./sections/assumptions";
import { renderEquipment } from "./sections/equipment";
import { renderTimeline } from "./sections/timeline";
import { renderNextSteps } from "./sections/nextSteps";
import { renderCredibility } from "./sections/credibility";

// Appendix renderers
import { renderScenarioComparison } from "./appendix/scenarioComparison";
import { renderCashflowTable } from "./appendix/cashflowTable";
import { renderOptimization } from "./appendix/optimization";

export function generateProfessionalPDF(
  doc: PDFKit.PDFDocument,
  simulation: SimulationData,
  lang: "fr" | "en" = "fr",
  allSiteSimulations: SimulationData[] = [],
  options?: {
    catalogEquipment?: Array<{ name: string; manufacturer: string; warranty: string; spec: string; category: string }>;
    constructionTimeline?: Array<{ step: string; duration: string; status?: string }>;
  }
): void {
  const ctx = createContext(doc, simulation, lang, options);

  // === MAIN SECTIONS (11) ===

  // Section 1: Cover
  renderCover(ctx);

  // Section 2: Project Snapshot
  renderProjectSnapshot(ctx);

  // Section 3: KPI Results
  renderKPIResults(ctx);

  // Section 4: Net Investment Breakdown (visual waterfall)
  renderInvestmentBreakdown(ctx);

  // Section 5: Roof Configuration (enriched with per-zone table)
  renderRoofConfiguration(ctx);

  // Section 6: Financial Projections (cashflow + cost of inaction)
  renderFinancialProjections(ctx);

  // Section 7: Assumptions & Exclusions
  renderAssumptions(ctx);

  // Sections 8, 9, 10 share a page: Equipment, Timeline, Next Steps
  doc.addPage();
  drawPageHeader(ctx, ctx.t("ÉQUIPEMENT, ÉCHÉANCIER ET PROCHAINES ÉTAPES", "EQUIPMENT, TIMELINE & NEXT STEPS"));
  doc.y = ctx.headerHeight + 25;

  // Section 8: Equipment & Warranties
  renderEquipment(ctx);

  // Section 9: Timeline
  renderTimeline(ctx);

  // Narrative transition to action
  const transition3 = getNarrativeTransition("resultsToAction", lang);
  doc.fontSize(8).fillColor("#4a5568").font("Helvetica-Oblique");
  doc.text(transition3, ctx.margin, doc.y, { width: ctx.contentWidth, align: "center" });
  doc.font("Helvetica");
  doc.moveDown(0.5);

  const act4 = getNarrativeAct("act4_action", lang);
  doc.fontSize(10).fillColor("#FFB005").font("Helvetica-Bold");
  doc.text(act4.title, ctx.margin, doc.y);
  doc.font("Helvetica");
  doc.fontSize(8).fillColor("#4a5568");
  doc.text(act4.subtitle, ctx.margin, doc.y + 2, { width: ctx.contentWidth });
  doc.moveDown(0.8);

  // Section 10: Next Steps
  renderNextSteps(ctx);

  // Footer for shared page
  drawPageFooter(ctx, ctx.t("Document confidentiel | Généré par kWh Québec | Équipement et prochaines étapes", "Confidential document | Generated by kWh Québec | Equipment & next steps"));

  // Section 11: They Trust Us (Credibility)
  renderCredibility(ctx);

  // === APPENDIX ===

  // Appendix A: Scenario Comparison (conditional)
  renderScenarioComparison(ctx, allSiteSimulations);

  // Appendix B: 25-Year Cashflow Table
  renderCashflowTable(ctx);

  // Appendix C: Optimization Analysis
  renderOptimization(ctx);
}
