import type { PDFContext } from "../types";
import { COLORS } from "../types";
import { drawRoundedRect, drawPageFooter } from "../helpers";
import { getAllStats, getTitle, getContactString, getValues, getCredibilityDescription, getCredibilityBenefits } from "@shared/brandContent";

export function renderCredibility(ctx: PDFContext) {
  const { doc, t, margin, contentWidth, pageWidth, pageHeight } = ctx;

  doc.addPage();

  doc.rect(0, 0, pageWidth, 80).fillColor(COLORS.blue).fill();
  doc.rect(0, 80, pageWidth, 4).fillColor(COLORS.gold).fill();

  doc.fontSize(24).fillColor(COLORS.white).font("Helvetica-Bold");
  doc.text(getTitle("trustUs", ctx.lang), margin, 30, { width: contentWidth, align: "center" });
  doc.font("Helvetica");

  let refY = 120;

  const credibilityStats = getAllStats(ctx.lang);
  const statColWidth = credibilityStats.length > 0 ? contentWidth / credibilityStats.length : contentWidth;

  credibilityStats.forEach((stat: any, i: number) => {
    const statX = margin + i * statColWidth;
    doc.fontSize(42).fillColor(COLORS.blue).font("Helvetica-Bold");
    doc.text(stat.value, statX, refY, { width: statColWidth, align: "center" });
    doc.fontSize(11).fillColor(COLORS.mediumGray).font("Helvetica");
    doc.text(stat.label, statX, refY + 50, { width: statColWidth, align: "center" });
  });

  refY += 100;

  doc.rect(margin + contentWidth * 0.3, refY, contentWidth * 0.4, 2).fillColor(COLORS.gold).fill();
  refY += 25;

  doc.fontSize(12).fillColor(COLORS.darkGray).font("Helvetica");
  doc.text(getCredibilityDescription(ctx.lang), margin, refY, { width: contentWidth, align: "center" });
  refY += 30;

  const values = getValues(ctx.lang);
  const valColWidth = contentWidth / values.length;
  values.forEach((val, i) => {
    const valX = margin + i * valColWidth;
    doc.fontSize(13).fillColor(COLORS.blue).font("Helvetica-Bold");
    doc.text(val.label, valX, refY, { width: valColWidth, align: "center" });
    doc.fontSize(9).fillColor(COLORS.mediumGray).font("Helvetica");
    doc.text(val.description, valX + 5, refY + 18, { width: valColWidth - 10, align: "center" });
  });

  refY += 60;

  const benefits = getCredibilityBenefits(ctx.lang);
  doc.fontSize(10).fillColor(COLORS.mediumGray).font("Helvetica");
  doc.text(benefits.join("  •  "), margin, refY, { width: contentWidth, align: "center" });
  refY += 30;

  doc.fontSize(18).fillColor(COLORS.blue).font("Helvetica-Bold");
  doc.text(getTitle("nextStep", ctx.lang), margin, refY, { width: contentWidth, align: "center" });

  doc.fontSize(12).fillColor(COLORS.darkGray).font("Helvetica");
  doc.text(getTitle("freeVisit", ctx.lang), margin, refY + 28, { width: contentWidth, align: "center" });

  doc.fontSize(16).fillColor(COLORS.gold).font("Helvetica-Bold");
  doc.text(getContactString(), margin, refY + 55, { width: contentWidth, align: "center" });

  drawPageFooter(ctx, t("Document confidentiel | Généré par kWh Québec", "Confidential document | Generated by kWh Québec"));
}
