import type { PDFContext } from "../types";
import { COLORS } from "../types";
import { formatCurrency, drawSimpleHeader, drawPageFooter } from "../helpers";
import { drawCashflowChart, drawCostOfInactionChart } from "../charts";

export function renderFinancialProjections(ctx: PDFContext) {
  const { doc, simulation, t, margin, contentWidth, pageWidth, pageHeight } = ctx;

  doc.addPage();
  drawSimpleHeader(ctx);
  doc.moveDown(2);

  // Section title
  doc.fontSize(18).fillColor(COLORS.blue).font("Helvetica-Bold");
  doc.text(t("PROJECTIONS FINANCIÈRES", "FINANCIAL PROJECTIONS"), margin, doc.y);
  doc.font("Helvetica");
  doc.y += 8;
  doc.rect(margin, doc.y, 200, 3).fillColor(COLORS.gold).fill();
  doc.y += 20;

  // Cash Flow Chart
  drawCashflowChart(
    ctx,
    margin,
    doc.y,
    contentWidth,
    180,
    simulation.cashflows || [],
    t("Flux de trésorerie et retour sur investissement", "Cash flow and return on investment")
  );

  doc.y += 210;

  // Cost of Inaction
  doc.fontSize(11).fillColor(COLORS.darkGray).font("Helvetica-Bold");
  doc.text(t("Pourquoi maintenant ? (coût de l'inaction)", "Why now? (cost of inaction)"), margin, doc.y);
  doc.font("Helvetica");
  doc.moveDown(1);

  const costChartY = doc.y;
  const costChartHeight = 150;

  drawCostOfInactionChart(ctx, margin, costChartY, contentWidth, costChartHeight);

  doc.y = costChartY + costChartHeight + 50;

  // Energy Security Section
  doc.fontSize(11).fillColor(COLORS.darkGray).font("Helvetica-Bold");
  doc.text(t("SÉCURITÉ ÉNERGÉTIQUE (RÉSILIENCE)", "ENERGY SECURITY (RESILIENCE)"), margin, doc.y);
  doc.font("Helvetica");
  doc.moveDown(0.5);

  doc.fontSize(10).fillColor(COLORS.mediumGray);
  doc.text(t("En cas de panne majeure, votre batterie peut maintenir vos opérations essentielles pendant :", "In case of major outage, your battery can maintain essential operations for:"), margin, doc.y);
  doc.moveDown(1);

  const criticalLoadKW = simulation.peakDemandKW * 0.3;
  const backupHours = criticalLoadKW > 0 ? simulation.battEnergyKWh / criticalLoadKW : 0;

  doc.fontSize(36).fillColor(COLORS.blue).font("Helvetica-Bold");
  doc.text(`${backupHours.toFixed(1)} ${t("Heures", "Hours")}`, margin, doc.y, { align: "right", width: contentWidth });
  doc.font("Helvetica");

  drawPageFooter(ctx, t("Document confidentiel | Généré par kWh Québec | Projections financières", "Confidential document | Generated by kWh Québec | Financial projections"));
}
