import type { PDFContext } from "../types";
import { COLORS } from "../types";
import { formatCurrency, drawRoundedRect, drawSimpleHeader, drawPageFooter } from "../helpers";
import { drawCashflowChart, drawCostOfInactionChart } from "../charts";

export function renderFinancialProjections(ctx: PDFContext) {
  const { doc, simulation, t, margin, contentWidth, pageWidth, pageHeight } = ctx;

  doc.addPage();
  drawSimpleHeader(ctx);
  doc.moveDown(2);

  // Section title
  doc.fontSize(18).fillColor(COLORS.blue).font("Helvetica-Bold");
  doc.text(t("PROJECTIONS FINANCIÈRES", "FINANCIAL PROJECTIONS"), margin, doc.y);
  doc.font("Helvetica");
  doc.y += 8;
  doc.rect(margin, doc.y, 200, 3).fillColor(COLORS.gold).fill();
  doc.y += 12;

  const paybackYears = simulation.simplePaybackYears || 0;
  if (paybackYears > 0) {
    const bannerY = doc.y;
    const bannerHeight = 50;
    
    // Draw the rounded rectangle banner with gold background
    drawRoundedRect(doc, margin, bannerY, contentWidth, bannerHeight, 8, COLORS.gold);
    
    // Draw the payback value in large bold white text (24px), centered
    doc.fontSize(24).fillColor(COLORS.white).font("Helvetica-Bold");
    doc.text(
      t(`${paybackYears.toFixed(1)} ans`, `${paybackYears.toFixed(1)} years`),
      margin,
      bannerY + 8,
      { width: contentWidth, align: "center" }
    );
    
    // Draw the subtitle in smaller white text (10px), centered
    doc.fontSize(10).fillColor(COLORS.white).font("Helvetica");
    doc.text(
      t("Retour sur investissement", "Payback period"),
      margin,
      bannerY + 32,
      { width: contentWidth, align: "center" }
    );
    
    doc.y = bannerY + bannerHeight + 15;
  } else {
    doc.y += 8;
  }

  // Cash Flow Chart — taller for better visibility
  drawCashflowChart(
    ctx,
    margin,
    doc.y,
    contentWidth,
    220,
    simulation.cashflows || [],
    t("Flux de trésorerie et retour sur investissement", "Cash flow and return on investment")
  );

  doc.y += 240;

  // Cost of Inaction — tighter spacing
  doc.fontSize(11).fillColor(COLORS.darkGray).font("Helvetica-Bold");
  doc.text(t("Pourquoi maintenant ? (coût de l'inaction)", "Why now? (cost of inaction)"), margin, doc.y);
  doc.font("Helvetica");
  doc.moveDown(0.8);

  const costChartY = doc.y;
  const costChartHeight = 150;

  drawCostOfInactionChart(ctx, margin, costChartY, contentWidth, costChartHeight);

  doc.y = costChartY + costChartHeight + 20;

  // Energy Security — only show when battery provides meaningful backup
  if (simulation.battEnergyKWh > 0) {
    const criticalLoadKW = simulation.peakDemandKW * 0.3;
    const backupHours = criticalLoadKW > 0 ? simulation.battEnergyKWh / criticalLoadKW : 0;

    const cardY = doc.y;
    const cardH = 60;
    drawRoundedRect(doc, margin, cardY, contentWidth, cardH, 8, COLORS.blue);

    doc.fontSize(10).fillColor(COLORS.white);
    doc.text(t("SÉCURITÉ ÉNERGÉTIQUE — En cas de panne, votre batterie maintient les opérations essentielles pendant :",
      "ENERGY SECURITY — In case of outage, your battery maintains essential operations for:"), margin + 15, cardY + 10, { width: contentWidth - 160 });

    doc.fontSize(28).fillColor(COLORS.gold).font("Helvetica-Bold");
    doc.text(`${backupHours.toFixed(1)}h`, margin + contentWidth - 130, cardY + 12, { width: 115, align: "center" });
    doc.font("Helvetica");
  }

  drawPageFooter(ctx, t("Document confidentiel | Généré par kWh Québec | Projections financières", "Confidential document | Generated by kWh Québec | Financial projections"));
}
