import type { PDFContext } from "../types";
import { COLORS } from "../types";
import { drawRoundedRect, drawPageHeader, drawPageFooter } from "../helpers";
import { getDesignFeeCovers, getClientProvides, getClientReceives, getContactString } from "@shared/brandContent";

export function renderNextSteps(ctx: PDFContext) {
  const { doc, t, margin, contentWidth } = ctx;

  // Own page
  doc.addPage();
  drawPageHeader(ctx, t("PROCHAINES ÉTAPES", "NEXT STEPS"));
  doc.y = ctx.headerHeight + 25;

  // Section title
  doc.fontSize(18).fillColor(COLORS.blue).font("Helvetica-Bold");
  doc.text(t("PROCHAINES ÉTAPES", "NEXT STEPS"), margin, doc.y);
  doc.font("Helvetica");
  doc.y += 5;
  doc.rect(margin, doc.y, 160, 3).fillColor(COLORS.gold).fill();
  doc.y += 20;

  // 3 blocks side by side
  const nsColWidth = (contentWidth - 20) / 3;
  const nsY = doc.y;
  const nsBlockH = 200;

  // Block A: Design fee covers
  drawRoundedRect(doc, margin, nsY, nsColWidth, nsBlockH, 6, COLORS.background);
  doc.roundedRect(margin, nsY, nsColWidth, nsBlockH, 6).strokeColor(COLORS.blue).lineWidth(1).stroke();

  doc.fontSize(9).fillColor(COLORS.blue).font("Helvetica-Bold");
  doc.text(t("Ce que couvre le", "What the design"), margin + 10, nsY + 10, { width: nsColWidth - 20 });
  doc.text(t("Design Fee (2 500$ + taxes)", "fee covers ($2,500 + taxes)"), margin + 10, nsY + 22, { width: nsColWidth - 20 });
  doc.font("Helvetica");

  const designCovers = getDesignFeeCovers(ctx.lang);
  let nsItemY = nsY + 45;
  designCovers.forEach((item: string) => {
    doc.fontSize(8).fillColor(COLORS.green).font("Helvetica-Bold");
    doc.text("✓", margin + 12, nsItemY);
    doc.font("Helvetica").fillColor(COLORS.darkGray);
    doc.text(item, margin + 24, nsItemY, { width: nsColWidth - 36 });
    nsItemY += 18;
  });

  // Block B: Client provides
  const nsCol2X = margin + nsColWidth + 10;
  drawRoundedRect(doc, nsCol2X, nsY, nsColWidth, nsBlockH, 6, COLORS.background);
  doc.roundedRect(nsCol2X, nsY, nsColWidth, nsBlockH, 6).strokeColor(COLORS.gold).lineWidth(1).stroke();

  doc.fontSize(9).fillColor(COLORS.gold).font("Helvetica-Bold");
  doc.text(t("Ce que vous", "What you"), nsCol2X + 10, nsY + 10, { width: nsColWidth - 20 });
  doc.text(t("devez fournir", "need to provide"), nsCol2X + 10, nsY + 22, { width: nsColWidth - 20 });
  doc.font("Helvetica");

  const clientProvides = getClientProvides(ctx.lang);
  nsItemY = nsY + 45;
  clientProvides.forEach((item: string) => {
    doc.fontSize(8).fillColor(COLORS.gold).font("Helvetica-Bold");
    doc.text("□", nsCol2X + 12, nsItemY);
    doc.font("Helvetica").fillColor(COLORS.darkGray);
    doc.text(item, nsCol2X + 24, nsItemY, { width: nsColWidth - 36 });
    nsItemY += 18;
  });

  // Block C: Client receives
  const nsCol3X = margin + 2 * (nsColWidth + 10);
  drawRoundedRect(doc, nsCol3X, nsY, nsColWidth, nsBlockH, 6, COLORS.background);
  doc.roundedRect(nsCol3X, nsY, nsColWidth, nsBlockH, 6).strokeColor(COLORS.green).lineWidth(1).stroke();

  doc.fontSize(9).fillColor(COLORS.green).font("Helvetica-Bold");
  doc.text(t("Ce que vous", "What you"), nsCol3X + 10, nsY + 10, { width: nsColWidth - 20 });
  doc.text(t("recevez", "receive"), nsCol3X + 10, nsY + 22, { width: nsColWidth - 20 });
  doc.font("Helvetica");

  const clientReceives = getClientReceives(ctx.lang);
  nsItemY = nsY + 45;
  clientReceives.forEach((item: string) => {
    doc.fontSize(8).fillColor(COLORS.green).font("Helvetica-Bold");
    doc.text("→", nsCol3X + 12, nsItemY);
    doc.font("Helvetica").fillColor(COLORS.darkGray);
    doc.text(item, nsCol3X + 24, nsItemY, { width: nsColWidth - 36 });
    nsItemY += 18;
  });

  // CTA Contact Box below the 3 columns
  const ctaY = nsY + nsBlockH + 25;
  drawRoundedRect(doc, margin, ctaY, contentWidth, 55, 8, COLORS.blue);

  doc.fontSize(14).fillColor(COLORS.white).font("Helvetica-Bold");
  doc.text(t("Contactez-nous pour planifier votre visite de site", "Contact us to schedule your site visit"), margin, ctaY + 10, { width: contentWidth, align: "center" });
  doc.font("Helvetica");

  doc.fontSize(11).fillColor(COLORS.gold);
  doc.text(getContactString(), margin, ctaY + 32, { width: contentWidth, align: "center" });

  drawPageFooter(ctx, t("Document confidentiel | Généré par kWh Québec | Prochaines étapes", "Confidential document | Generated by kWh Québec | Next steps"));
}
