import type { PDFContext } from "../types";
import { COLORS } from "../types";
import { drawRoundedRect, drawPageHeader, drawPageFooter } from "../helpers";
import { getProjectSnapshotLabels } from "../../brandContent";

export function renderProjectSnapshot(ctx: PDFContext) {
  const { doc, simulation, t, margin, contentWidth, pageWidth, pageHeight, headerHeight } = ctx;

  doc.addPage();

  // Header
  drawPageHeader(ctx, t("APERÇU DU PROJET", "PROJECT SNAPSHOT"));

  doc.y = headerHeight + 25;

  // Section title
  doc.fontSize(22).fillColor(COLORS.blue).font("Helvetica-Bold");
  doc.text(t("APERÇU DU PROJET", "PROJECT SNAPSHOT"), margin, doc.y);
  doc.font("Helvetica");
  doc.y += 8;
  doc.rect(margin, doc.y, 180, 3).fillColor(COLORS.gold).fill();
  doc.y += 20;

  // Site info
  doc.fontSize(14).fillColor(COLORS.darkGray).font("Helvetica-Bold");
  doc.text(simulation.site.name, margin, doc.y);
  doc.font("Helvetica");
  doc.fontSize(11).fillColor(COLORS.mediumGray);
  const snapLocation = [simulation.site.address, simulation.site.city, simulation.site.province || "QC"].filter(Boolean).join(", ");
  doc.text(snapLocation || "Québec", margin, doc.y + 20);
  doc.y += 50;

  // Snapshot data grid
  const snapLabels = getProjectSnapshotLabels(ctx.lang);
  const snapData: [string, string][] = [
    [snapLabels.annualConsumption.label, `${(simulation.annualConsumptionKWh || 0).toLocaleString()} kWh`],
    [snapLabels.peakDemand.label, `${(simulation.peakDemandKW || 0).toFixed(0)} kW`],
    [snapLabels.solarCapacity.label, `${simulation.pvSizeKW.toFixed(0)} kWc`],
    [snapLabels.batteryCapacity.label, simulation.battEnergyKWh > 0 ? `${simulation.battEnergyKWh.toFixed(0)} kWh / ${simulation.battPowerKW.toFixed(0)} kW` : t("Non inclus", "Not included")],
    [snapLabels.estimatedProduction.label, `${((simulation.pvSizeKW * 1035) || 0).toLocaleString()} kWh`],
    [snapLabels.selfConsumptionRate.label, `${(simulation.selfSufficiencyPercent || 0).toFixed(0)}%`],
  ];

  const snapColWidth = (contentWidth - 20) / 2;
  const snapRowHeight = 55;
  snapData.forEach(([label, value], idx) => {
    const col = idx % 2;
    const row = Math.floor(idx / 2);
    const sx = margin + col * (snapColWidth + 20);
    const sy = doc.y + row * (snapRowHeight + 10);

    drawRoundedRect(doc, sx, sy, snapColWidth, snapRowHeight, 6, COLORS.background);
    doc.roundedRect(sx, sy, snapColWidth, snapRowHeight, 6).strokeColor(COLORS.lightGray).lineWidth(0.5).stroke();

    doc.fontSize(9).fillColor(COLORS.mediumGray);
    doc.text(label, sx + 12, sy + 10, { width: snapColWidth - 24 });
    doc.fontSize(16).fillColor(COLORS.blue).font("Helvetica-Bold");
    doc.text(value, sx + 12, sy + 28, { width: snapColWidth - 24 });
    doc.font("Helvetica");
  });

  doc.y += 3 * (snapRowHeight + 10) + 20;

  // Aerial image placeholder
  drawRoundedRect(doc, margin, doc.y, contentWidth, 60, 6, COLORS.background);
  doc.roundedRect(margin, doc.y, contentWidth, 60, 6).strokeColor(COLORS.lightGray).lineWidth(0.5).stroke();
  doc.fontSize(10).fillColor(COLORS.mediumGray);
  doc.text(t("Image aérienne du site — à insérer lors de la visite de site", "Aerial site image — to be inserted during site visit"), margin + 20, doc.y + 22, { width: contentWidth - 40, align: "center" });

  // Footer
  drawPageFooter(ctx, t("Document confidentiel | Généré par kWh Québec | Aperçu du projet", "Confidential document | Generated by kWh Québec | Project snapshot"));
}
