import type { PDFContext } from "../types";
import { COLORS } from "../types";
import { formatCurrency, drawSimpleHeader, drawPageFooter } from "../helpers";

export function renderCashflowTable(ctx: PDFContext) {
  const { doc, simulation, t, margin, contentWidth, pageWidth, pageHeight, dateStr } = ctx;

  if (!simulation.cashflows || simulation.cashflows.length === 0) {
    return;
  }

  doc.addPage();
  drawSimpleHeader(ctx);
  doc.moveDown(2);

  // Appendix label
  doc.fontSize(10).fillColor(COLORS.gold).font("Helvetica-Bold");
  doc.text(t("ANNEXE B", "APPENDIX B"), margin, doc.y);
  doc.font("Helvetica");
  doc.y += 5;

  // Financial Table Title
  doc.fontSize(11).fillColor(COLORS.darkGray).font("Helvetica-Bold");
  doc.text(t("TABLEAU DES FLUX FINANCIERS", "FINANCIAL CASH FLOW TABLE"), margin, doc.y);
  doc.font("Helvetica");
  doc.moveDown(1);

  // Table Headers
  const tableX = margin;
  const tableY = doc.y;
  const colWidths = [40, 70, 70, 70, 70, 70, 80];
  const headers = [
    t("An", "Year"),
    t("Revenu", "Rev"),
    t("O&M", "O&M"),
    t("Invest", "Invest"),
    t("Taxes", "Tax"),
    t("NET", "NET"),
    t("CUMUL", "CUMUL"),
  ];

  // Header row
  doc.fontSize(8).fillColor(COLORS.white).font("Helvetica-Bold");
  let headerX = tableX;
  headers.forEach((header, i) => {
    doc.rect(headerX, tableY, colWidths[i], 18).fillColor(COLORS.blue).fill();
    doc.fillColor(COLORS.white).text(header, headerX + 3, tableY + 5, { width: colWidths[i] - 6, align: "center" });
    headerX += colWidths[i];
  });
  doc.font("Helvetica");

  // Data rows
  let rowY = tableY + 18;
  const rowHeight = 14;
  const cashflowsToShow = (simulation.cashflows || []).slice(0, 26); // Years 0-25

  cashflowsToShow.forEach((cf, idx) => {
    if (rowY > pageHeight - 60) {
      doc.addPage();
      drawSimpleHeader(ctx);
      rowY = margin + 40;
    }

    const bgColor = idx % 2 === 0 ? COLORS.white : "#F8F8F8";
    let cellX = tableX;

    const rowData = [
      cf.year.toString(),
      cf.revenue > 0 ? formatCurrency(cf.revenue, true) : "",
      cf.opex < 0 ? formatCurrency(cf.opex, true) : "",
      cf.investment !== 0 ? formatCurrency(cf.investment, true) : "",
      (cf.dpa || 0) + (cf.incentives || 0) !== 0 ? formatCurrency((cf.dpa || 0) + (cf.incentives || 0), true) : "",
      formatCurrency(cf.netCashflow, true),
      formatCurrency(cf.cumulative, true),
    ];

    rowData.forEach((value, i) => {
      doc.rect(cellX, rowY, colWidths[i], rowHeight).fillColor(bgColor).fill();
      doc.rect(cellX, rowY, colWidths[i], rowHeight).strokeColor(COLORS.lightGray).lineWidth(0.5).stroke();

      const textColor = i === 6 && cf.cumulative < 0 ? COLORS.red : (i === 6 && cf.cumulative > 0 ? COLORS.green : COLORS.darkGray);
      doc.fontSize(7).fillColor(textColor).text(value, cellX + 2, rowY + 3, { width: colWidths[i] - 4, align: "right" });
      cellX += colWidths[i];
    });

    rowY += rowHeight;
  });

  drawPageFooter(ctx, t("Document confidentiel | Généré par kWh Québec | Annexe B", "Confidential document | Generated by kWh Québec | Appendix B"));
}
