// server/middleware/serverValidation.ts
// Centralized request body validation using Zod schemas
// Generated by Improvement Agent (2026-02-27)
// Resolves: P2 [Agent] Implémenter validation côté serveur manquante

import { Request, Response, NextFunction } from "express";
import { z, ZodError, ZodSchema } from "zod";

// ============================================================================
// MIDDLEWARE FACTORY
// ============================================================================

/**
 * Creates Express middleware that validates req.body against a Zod schema.
 * On success, replaces req.body with parsed (sanitized) data.
 * On failure, returns 400 with structured error details.
 */
export function validateBody<T extends ZodSchema>(schema: T) {
  return (req: Request, res: Response, next: NextFunction): void => {
    const result = schema.safeParse(req.body);
    if (!result.success) {
      const errors = result.error.errors.map((e) => ({
        field: e.path.join("."),
        message: e.message,
      }));
      res.status(400).json({ error: "Validation failed", details: errors });
      return;
    }
    req.body = result.data;
    next();
  };
}

// ============================================================================
// SHARED VALIDATORS
// ============================================================================

export const emailField = z.string().email("Invalid email").max(255).trim();
export const phoneField = z.string().regex(/^[\d\s\-+()]+$/, "Invalid phone").max(20).optional();
export const currencyField = z.number().min(0).max(999999999.99).finite();
export const percentField = z.number().min(0).max(100).finite();
export const uuidField = z.string().uuid("Invalid UUID");

// ============================================================================
// DESIGN SCHEMAS
// ============================================================================

export const designCreationSchema = z.object({
  designName: z.string().min(1).max(255).trim(),
  simulationRunId: z.string().uuid().optional(),
  moduleModelId: z.string().max(255).optional(),
  inverterModelId: z.string().max(255).optional(),
  batteryModelId: z.string().max(255).optional(),
  pvSizeKW: z.number().min(0.1).max(10000).finite(),
  batteryEnergyKWh: z.number().min(0).max(1000000).finite(),
  batteryPowerKW: z.number().min(0).max(100000).finite(),
  marginPercent: percentField,
});

export const designUpdateSchema = designCreationSchema.partial();

// ============================================================================
// OPPORTUNITY SCHEMAS
// ============================================================================

export const opportunityUpdateSchema = z.object({
  stage: z.enum(["lead", "qualified", "proposal", "negotiation", "won", "lost", "archived"]).optional(),
  probability: percentField.optional(),
  lostReason: z.enum(["budget", "timeline", "competitor", "roof_condition", "lease_issues", "customer_decision", "other"]).optional(),
  lostNotes: z.string().max(2000).optional(),
  notes: z.string().max(5000).optional(),
});

// ============================================================================
// CLIENT SCHEMAS
// ============================================================================

export const clientUpdateSchema = z.object({
  companyName: z.string().min(1).max(255).optional(),
  firstName: z.string().min(1).max(100).optional(),
  lastName: z.string().min(1).max(100).optional(),
  email: emailField.optional(),
  phone: phoneField,
  streetAddress: z.string().max(255).optional(),
  city: z.string().max(100).optional(),
  province: z.string().max(100).optional(),
  postalCode: z.string().regex(/^[A-Za-z0-9\s\-]{3,10}$/, "Invalid postal code").optional(),
  language: z.enum(["fr", "en"]).optional(),
  archived: z.boolean().optional(),
});

// ============================================================================
// CONSTRUCTION SCHEMAS
// ============================================================================

export const constructionAgreementUpdateSchema = z.object({
  status: z.enum(["draft", "pending", "accepted", "rejected", "completed"]).optional(),
  startDate: z.coerce.date().optional(),
  endDate: z.coerce.date().optional(),
  totalAmount: currencyField.optional(),
  depositAmount: currencyField.optional(),
  paymentTerms: z.string().max(2000).optional(),
  notes: z.string().max(5000).optional(),
});

export const milestoneUpdateSchema = z.object({
  title: z.string().min(1).max(255).optional(),
  status: z.enum(["pending", "in_progress", "completed", "blocked"]).optional(),
  dueDate: z.coerce.date().optional(),
  completedAt: z.coerce.date().optional(),
  description: z.string().max(2000).optional(),
  assignedTo: z.string().uuid().optional(),
  percentComplete: z.number().int().min(0).max(100).optional(),
});

// ============================================================================
// SITE ANALYSIS SCHEMAS
// ============================================================================

export const potentialAnalysisSchema = z.object({
  constraintFactor: z.number().min(0.1).max(1).optional(),
  assumptions: z.record(z.union([z.string(), z.number(), z.boolean(), z.null()])).optional(),
});

export const monteCarloSchema = z.object({
  config: z.object({
    iterations: z.number().int().min(100).max(10000).optional(),
    confidenceLevel: z.number().min(0.8).max(0.99).optional(),
    variables: z.record(z.unknown()).optional(),
  }).optional(),
});

// ============================================================================
// EMAIL SCHEMAS
// ============================================================================

export const sendEmailSchema = z.object({
  recipientEmail: emailField,
  recipientName: z.string().max(255).optional(),
  subject: z.string().min(1).max(255).trim(),
  body: z.string().min(1).max(10000),
  language: z.enum(["fr", "en"]).default("fr").optional(),
});

// ============================================================================
// PUBLIC AGREEMENT SCHEMAS
// ============================================================================

export const agreementSigningSchema = z.object({
  name: z.string().min(1).max(255).trim(),
  email: emailField,
  signatureData: z.string().min(10, "Invalid signature data"),
  title: z.string().max(100).optional(),
  city: z.string().max(100).optional(),
});

// ============================================================================
// ADMIN CONTENT SCHEMAS
// ============================================================================

export const blogUpdateSchema = z.object({
  slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "Invalid slug format").max(255).optional(),
  titleFr: z.string().min(1).max(255).optional(),
  titleEn: z.string().min(1).max(255).optional(),
  contentFr: z.string().max(50000).optional(),
  contentEn: z.string().max(50000).optional(),
  metaDescriptionFr: z.string().max(160).optional(),
  metaDescriptionEn: z.string().max(160).optional(),
  category: z.string().max(100).optional(),
  status: z.enum(["draft", "published", "archived"]).optional(),
  publishedAt: z.coerce.date().optional(),
});

// ============================================================================
// SANITIZATION MIDDLEWARE
// ============================================================================

/**
 * Strips dangerous HTML/JS from string fields in req.body.
 * Apply before validation for defense-in-depth.
 */
export function sanitizeBody(req: Request, _res: Response, next: NextFunction): void {
  if (typeof req.body !== "object" || req.body === null) return next();

  const sanitize = (val: unknown): unknown => {
    if (typeof val === "string") {
      return val
        .replace(/<script[^>]*>.*?<\/script>/gi, "")
        .replace(/javascript:/gi, "")
        .replace(/on\w+=\s*/gi, "");
    }
    if (Array.isArray(val)) return val.map(sanitize);
    if (typeof val === "object" && val !== null) {
      return Object.fromEntries(
        Object.entries(val).map(([k, v]) => [k, sanitize(v)])
      );
    }
    return val;
  };

  req.body = sanitize(req.body);
  next();
}

/**
 * Rejects NaN/Infinity in numeric fields.
 */
export function validateNumbers(req: Request, res: Response, next: NextFunction): void {
  const check = (obj: unknown): boolean => {
    if (typeof obj === "number" && !isFinite(obj)) return false;
    if (Array.isArray(obj)) return obj.every(check);
    if (typeof obj === "object" && obj !== null) return Object.values(obj).every(check);
    return true;
  };

  if (!check(req.body)) {
    res.status(400).json({ error: "Invalid numeric value: must be finite" });
    return;
  }
  next();
}

// ============================================================================
// PRE-BUILT MIDDLEWARE EXPORTS
// ============================================================================

export const validate = {
  designCreation: validateBody(designCreationSchema),
  designUpdate: validateBody(designUpdateSchema),
  opportunityUpdate: validateBody(opportunityUpdateSchema),
  clientUpdate: validateBody(clientUpdateSchema),
  constructionAgreementUpdate: validateBody(constructionAgreementUpdateSchema),
  milestoneUpdate: validateBody(milestoneUpdateSchema),
  potentialAnalysis: validateBody(potentialAnalysisSchema),
  monteCarlo: validateBody(monteCarloSchema),
  sendEmail: validateBody(sendEmailSchema),
  agreementSigning: validateBody(agreementSigningSchema),
  blogUpdate: validateBody(blogUpdateSchema),
};
